apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tikto
  namespace: argocd
spec:
  description: TikTo application environments
  sourceRepos:
    - https://github.com/Flavoriy/gitops-manifest.git
  destinations:
    - server: "*"
      namespace: tikto-dev
    - server: "*"
      namespace: tikto-prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

