apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tikto-ingress
  namespace: tikto-prod
  annotations:
    # Use AWS Application Load Balancer (ALB)
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-port: '15021'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingress
                port:
                  number: 80
