apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tikto-prod

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - secret-store.yaml
  - external-secret.yaml
  - pdb.yaml
  - ingress.yaml
  - services-canary.yaml
  - rollout.yaml
  - analysis-smoke-test.yaml
  - analysis-opensearch.yaml
  - istio-gateway.yaml
  - istio-virtualservice.yaml
  - services-backend-canary.yaml
  - rollouts-backend.yaml

patches:
  - path: patch-image.yaml
  - path: patch-replicas.yaml
  - path: patch-scheduling.yaml
  - path: patch-service.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tikto
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tikto
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: tikto-gateway
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: tikto-gateway

commonLabels:
  app.kubernetes.io/instance: tikto-prod
  app.kubernetes.io/environment: prod
