apiVersion: v1
kind: Service
metadata:
  name: tikto
  annotations:
    link.argocd.argoproj.io/external-link: http://18.136.110.57:30443
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30443
