apiVersion: v1
kind: ResourceQuota
metadata:
  name: tikto-prod-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 3Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "6"
    secrets: "20"
    configmaps: "20"

