apiVersion: v1
kind: Service
metadata:
  name: tikto-gateway-stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 4000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-gateway-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 4000
      targetPort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tikto-gateway-vs
spec:
  hosts:
    - tikto-gateway
  http:
    - name: primary
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: tikto-gateway-canary
            port:
              number: 4000
    - route:
        - destination:
            host: tikto-gateway-stable
            port:
              number: 4000
          weight: 100
        - destination:
            host: tikto-gateway-canary
            port:
              number: 4000
          weight: 0
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-profile-api-stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: profile-api
  ports:
    - name: http
      port: 4100
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-profile-api-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: profile-api
  ports:
    - name: http
      port: 4100
      targetPort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tikto-profile-api-vs
spec:
  hosts:
    - tikto-profile-api
  http:
    - name: primary
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: tikto-profile-api-canary
            port:
              number: 4100
    - route:
        - destination:
            host: tikto-profile-api-stable
            port:
              number: 4100
          weight: 100
        - destination:
            host: tikto-profile-api-canary
            port:
              number: 4100
          weight: 0
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-tasks-api-stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: tasks-api
  ports:
    - name: http
      port: 4200
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-tasks-api-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: tasks-api
  ports:
    - name: http
      port: 4200
      targetPort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tikto-tasks-api-vs
spec:
  hosts:
    - tikto-tasks-api
  http:
    - name: primary
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: tikto-tasks-api-canary
            port:
              number: 4200
    - route:
        - destination:
            host: tikto-tasks-api-stable
            port:
              number: 4200
          weight: 100
        - destination:
            host: tikto-tasks-api-canary
            port:
              number: 4200
          weight: 0
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-calendar-api-stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: calendar-api
  ports:
    - name: http
      port: 4300
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-calendar-api-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: calendar-api
  ports:
    - name: http
      port: 4300
      targetPort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tikto-calendar-api-vs
spec:
  hosts:
    - tikto-calendar-api
  http:
    - name: primary
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: tikto-calendar-api-canary
            port:
              number: 4300
    - route:
        - destination:
            host: tikto-calendar-api-stable
            port:
              number: 4300
          weight: 100
        - destination:
            host: tikto-calendar-api-canary
            port:
              number: 4300
          weight: 0
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-dashboard-api-stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: dashboard-api
  ports:
    - name: http
      port: 4400
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: tikto-dashboard-api-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tikto
    app.kubernetes.io/component: dashboard-api
  ports:
    - name: http
      port: 4400
      targetPort: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tikto-dashboard-api-vs
spec:
  hosts:
    - tikto-dashboard-api
  http:
    - name: primary
      match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: tikto-dashboard-api-canary
            port:
              number: 4400
    - route:
        - destination:
            host: tikto-dashboard-api-stable
            port:
              number: 4400
          weight: 100
        - destination:
            host: tikto-dashboard-api-canary
            port:
              number: 4400
          weight: 0
