apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tikto-dev
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://18.139.31.55:30443
spec:
  project: default
  source:
    repoURL: https://github.com/Flavoriy/gitops-manifest.git
    targetRevision: main
    path: apps/tikto/overlays/dev
  destination:
    name: k3s-dev
    namespace: tikto-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
