apiVersion: v1
kind: ConfigMap
metadata:
  name: tikto-config
data:
  APP_ENV: dev
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"
  TIKTO_PROFILE_API_URL: http://tikto-profile-api:4100
  TIKTO_TASKS_API_URL: http://tikto-tasks-api:4200
  TIKTO_CALENDAR_API_URL: http://tikto-calendar-api:4300
  TIKTO_DASHBOARD_API_URL: http://tikto-dashboard-api:4400
  NEXT_PUBLIC_APP_URL: http://18.139.31.55:30443
  NEXT_PUBLIC_SUPABASE_URL: https://replace-dev-project.supabase.co

