apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikto
spec:
  template:
    spec:
      containers:
        - name: tikto
          image: ghcr.io/flavoriy/tikto-web:dev-39-c134537a20548f8fede0b7af6f042d39c62848a0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikto-profile-api
spec:
  template:
    spec:
      containers:
        - name: profile-api
          image: ghcr.io/flavoriy/tikto-profile:dev-39-c134537a20548f8fede0b7af6f042d39c62848a0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikto-tasks-api
spec:
  template:
    spec:
      containers:
        - name: tasks-api
          image: ghcr.io/flavoriy/tikto-tasks:dev-39-c134537a20548f8fede0b7af6f042d39c62848a0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikto-calendar-api
spec:
  template:
    spec:
      containers:
        - name: calendar-api
          image: ghcr.io/flavoriy/tikto-calendar:dev-39-c134537a20548f8fede0b7af6f042d39c62848a0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikto-dashboard-api
spec:
  template:
    spec:
      containers:
        - name: dashboard-api
          image: ghcr.io/flavoriy/tikto-dashboard:dev-39-c134537a20548f8fede0b7af6f042d39c62848a0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikto-gateway
spec:
  template:
    spec:
      containers:
        - name: gateway
          image: ghcr.io/flavoriy/tikto-gateway:dev-39-c134537a20548f8fede0b7af6f042d39c62848a0