apiVersion: v1
kind: ResourceQuota
metadata:
  name: tikto-dev-quota
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 768Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: "4"
    services: "4"
    secrets: "10"
    configmaps: "10"

